version: "3.8"

services:
  # Applications
  catalog-service:
    depends_on:
      - bookshop-postgres
    image: "ghcr.io/bladespring/bookshop-catalog-service:0.0.1"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookshop-postgres:5432/bookshopdb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  config-service:
    image: "ghcr.io/bladespring/bookshop-config-service:0.0.1"
    ports:
      - 8888:8888
      - 8002:8002
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002

  order-service:
    image: "ghcr.io/bladespring/bookshop-order-service:0.0.1"
    ports:
      - 9002:9002
      - 8003:8003
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8003
      - SPRING_R2DBC_URL=r2dbc:postgresql://bookshop-postgres:5432/bookshopdb_order
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - BOOKSHOP_CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_FLYWAY_URL=jdbc:postgresql://bookshop-postgres:5432/bookshopdb_order

  # Backing Services
  bookshop-postgres:
    image: "postgres:14.8"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user 
      - POSTGRES_PASSWORD=password 
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql 